### ISSUE TITLE
Cancel not working on ModalTextField

### ISSUE THREAD

**Issue by satan87** [iDara09/BDUIKnit#1]
Hello,

Great work on the component, they're very nice and easy to use.

I believe there is a bug on the ModelTextField with the cancel option.
Here how to reproduce it:
- Click the button
- Add a text
- Save  -> the test will be display
- Click the button
- Click cancel -> no problem
- Click the button
- Click the "Erase all" at the end of the line
- Click cancel -> ISSUE: The text has disappeared

Thanks,
Nicolas

**Comment by bdaralan** [comment]
Hey Nicolas, thank you for reporting the issue.

I have looked at it, it is not a bug but intended. The use case should be that you store your own text. The model is only used to update the view, developer should handle the data.

I will update the sample code soon, but here is a quick demo.

``` Swift
@State private var yourText = ""

@State private var textFieldModel = BDModalTextFieldModel()

func presentModalTextField() {
    
    // assign your text to the text field's text before present
    textFieldModel.text = yourText 
 
    textFieldModel.onCancel = {
        // ignore to update yourText and dismiss
        self.textFieldModel.isFirstResponder = false
        self.presentSheet = false
    }

    textFieldModel.onCommit = {
        // grab the text from the text field and dismiss
        self.yourText = self.textFieldModel.text 
        self.textFieldModel.isFirstResponder = false
        self.presentSheet = false
    }

    textFieldModel.onReturnKey = {
        // grab the text from the text field and dismiss
        self.yourText = self.textFieldModel.text
        self.textFieldModel.isFirstResponder = false
        self.presentSheet = false
    }
}

```

**Comment by satan87** [comment]
Thank you for the quick answer .. it is working well thanks.
