### ISSUE TITLE
Cancel button on ModalTextView

### ISSUE THREAD

**Issue by satan87** [iDara09/BDUIKnit#2]
Hey,

Any plan to add the cancel button on the ModalTextView ?

Thanks,
Nicolas

**Comment by bdaralan** [comment]
Yes, I will and it will work the same way as ModalTextField

**Comment by satan87** [comment]
Thanks ;)
It will save me from my ugly multiline view updater ...

**Comment by bdaralan** [comment]
Added in 1.1.11 release
