### ISSUE TITLE
Button Title to use NSLocalizedString instead of String

### ISSUE THREAD

**Issue by satan87** [iDara09/BDUIKnit#6]
Hello,

When using Button 
```
let favoriteItem = BDButtonTrayItem(title: "Favorite Only", systemImage: "star") { item in
```

The title is not passed as a localizable string.

I did a quick check and it is Display in a Text component, which supports NSLocalizedString.

Nicolas

**Comment by bdaralan** [comment]
Hi,

Thanks for the feedback. I am still new to all the localize setup, so I guess `Text` object only turns string literal to localized string.

I will add `Text(LocalizedStringKey(title))` in the future update and will also look for other places where I can localized them.

**Comment by bdaralan** [comment]
Added in 1.1.15 release
